# Generated by Django 5.1.5 on 2025-04-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_category_post_category_repost"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="Anonymous User", max_length=100, unique=True
            ),
        ),
    ]
