# Generated by Django 5.1.5 on 2025-04-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled Post", max_length=200),
        ),
    ]
