# Generated by Django 5.1.5 on 2025-04-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="password", max_length=100),
        ),
    ]
