# Generated by Django 5.1.5 on 2025-04-28 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
