# Generated by Django 5.1.5 on 2025-04-30 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_remove_post_comment_count_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="repost",
            unique_together=set(),
        ),
    ]
