# Generated by Django 5.1.5 on 2025-04-30 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the web-hosted image",
                max_length=500,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
