# Generated by Django 5.1.5 on 2025-05-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0010_post_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
