# Generated by Django 5.1.5 on 2025-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_post_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
