# Generated by Django 5.1.5 on 2025-05-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0013_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
