# Generated by Django 5.1.5 on 2025-05-01 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0014_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
