# Generated by Django 5.1.5 on 2025-05-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0016_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
