# Generated by Django 5.1.5 on 2025-05-01 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_userprofile_bio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
    ]
