# Generated by Django 5.1.5 on 2025-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0018_delete_user_remove_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
