# Generated by Django 5.1.5 on 2025-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_fb", "0003_image_statusimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
