# Generated by Django 5.1.5 on 2025-03-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_fb", "0004_alter_image_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
