# Generated by Django 5.1.5 on 2025-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_fb", "0005_image_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="message",
        ),
        migrations.RemoveField(
            model_name="statusimage",
            name="message",
        ),
        migrations.AddField(
            model_name="image",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
    ]
